### ISSUE TITLE
Me ofrezco como mentor.

### ISSUE THREAD

**Issue by pjmolina** [nodeschool/seville#2]
Hola.
Me encanta la idea de que el mundo NodeJS se mueva en Sevilla y quiero apoyarlo ofrecinedome como mentor.

Desde Icinetic tenemos experiencia con NodeJS y ponemos a disposición de todos los asistentes la herramienta: [AppNow](https://appnow.radarconline.com/) que permite construir Restfull Backends en NodeJS rapidamente.

Me interesa vuestra opinion en dos aspectos:
1. Recabar feedback sobre los expertos en node para mejorarlo. 
2. Como recurso de formacion para gente que se inicia en NodeJS. 

Saludos

**Comment by leolara** [comment]
Interesante AppNow, es tuya?

**Comment by leolara** [comment]
btw, el link en https://appnow.radarconline.com/ a github esta mal

**Comment by pjmolina** [comment]
¡Si!, es nuestra. 
Gracias Leo: el link a github es genérico a Github como tal. No a un contenido especifico.

**Comment by leolara** [comment]
Pero dice, download the full source code or push it to Github. Y cuando haces click te lleva al homepage de github no al codigo fuente, igual lo he encontrado aquí:

https://github.com/Icinetic/reference-appnow

**Comment by pjmolina** [comment]
Entiendo ahora el origen de la confusión. Gracias por comentarlo.

AppNow no es un framework para descargar desde github y usar directamente.

Es un servicio. Tienes que logarte y usarlo. Al final de proceso, opcionalmente AppNow como característica puede entregar el código construido en un repo github bajo tu cuenta, o desplegar en heroku, bluemix, o cloudshare.

Quitaremos el enlace a github que parece que esta generando confusion.

La [reference-appnow](https://github.com/Icinetic/reference-appnow) es eso: solo un ejemplo de lo que se puede hacer. En los videos puedes ver otros ejemplos.

**Comment by leolara** [comment]
Entiendo ahora!!

2015-05-20 14:23 GMT+02:00 Pedro J. Molina notifications@github.com:

**Comment by beltran-rubo** [comment]
Hola Pedro,

Gracias por ofrecerte como mentor! Te añado a la web de GitHub y de Meetup. 

Tiene buena pinta AppNow! Y tengo unas cuantas preguntas acerca de la implementación que te preguntaré el sábado. En principio la idea es que los asistentes se familiaricen con Node.js con los tutoriales de NodeSchool y tan sólo haré una presentación breve de las ventajas de Node.js para intentar motivar a los desarrolladores. Mencionaré AppNow para los que quieran usarlo.

Un saludo.

**Comment by pjmolina** [comment]
Estupendo Beltran. Nos vemos el sábado.

El 20 de mayo de 2015, 20:49, Beltran notifications@github.com escribió:

> Hola Pedro,
> 
> Gracias por ofrecerte como mentor! Te añado a la web de GitHub y de
> Meetup.
> 
> Tiene buena pinta AppNow! Y tengo unas cuantas preguntas acerca de la
> implementación que te preguntaré el sábado. En principio la idea es que los
> asistentes se familiaricen con Node.js con los tutoriales de NodeSchool y
> tan sólo haré una presentación breve de las ventajas de Node.js para
> intentar motivar a los desarrolladores. Mencionaré AppNow para los que
> quieran usarlo.
> 
> Un saludo.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nodeschool/seville/issues/2#issuecomment-103992499.

## 

Dr. Pedro J. Molina
pjmolina@gmail.com
http://pjmolina.com
